import { ScrollView, LineEdit } from "std-widgets.slint";

export TableCell := Rectangle {
    property<bool> input;
    property<bool> active;
    property<string> text;
    property<string> placeholder-text;
    property<TextHorizontalAlignment> horizontal-alignment: left;

    callback accepted(string);

    accepted(val) => {
        root.text = val;
    }

    forward-focus: edit;

    edit := LineEdit {
        visible: edit.has-focus ? active : false;
        placeholder-text: root.placeholder-text;
        width: 100%;
        height: 100%;
        accepted(val) => {
            root.accepted(val);
            active = false;
        }
    }

    touch-area := TouchArea {
        enabled: input;
        clicked => {
            edit.text = root.text;
            edit.focus();
            active = true;
        }
    }

    text := Text {
        visible: !edit.visible;
        preferred-width: 0;
        width: root.width - 12px;
        x: input ? 8px : 6px;
        vertical-alignment: center;
        horizontal-alignment: root.horizontal-alignment;
        height: 100%;
        text: {
            if (input && root.text == "") {
                root.placeholder-text
            } else {
                root.text
            }
        }
        opacity: {
            if (input && root.text == "") {
                0.5
            } else {
                1
            }
        }
        overflow: elide;
    }
}

export TableRow := Rectangle {
    property<int> n: 1;
    height: 30px;
    background: {
        if (mod(n, 2) == 0) {
            #eee
        } else {
            #fff
        }
    }

    HorizontalLayout {
        @children
    }
}

export Table := Rectangle {
    property<[string]> column-names: [];
    property<[float]> column-widths: [];
    property<int> row-count: 0;
    property<length> row-height: 30px;
    property viewport-width <=> scroll-view.viewport-width;
    property viewport-height <=> scroll-view.viewport-height;
    property viewport-x <=> scroll-view.viewport-x;
    property viewport-y <=> scroll-view.viewport-y;

    // header
    Rectangle {
        height: 30px;
        width: scroll-view.visible-width;
        HorizontalLayout {
            for name[index] in column-names: TableCell {
                horizontal-stretch: {
                    if (column-names.length == column-widths.length) {
                        column-widths[index]
                    } else {
                        1
                    }
                }

                text: name;
            }
        }
    }

    // body
    scroll-view := ScrollView {
        y: 30px;
        height: parent.height - 30px;
        viewport-width: 0;
        viewport-height: row-height * row-count;
        VerticalLayout {
            width: parent.visible-width;
            @children
        }
    }
}